CREATE DATABASE burgers_db;
USE burgers_db;
CREATE TABLE burgers (id INTEGER(6) AUTO_INCREMENT NOT NULL,
 burger_name VARCHAR(30) NOT NULL,
 devoured BOOLEAN,
 date1 DATETIME DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (id));